apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2048-ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: k8s-game2048-ingress
    # alb.ingress.kubernetes.io/subnets: subnet-xxx,subnet-xxx,subnet-xxx
spec:
  # This can be omitted if you have a default ingressClass in cluster: the one with ingressclass.kubernetes.io/is-default-class: "true"  annotation
  ingressClassName: eks-auto-mode-ic # This matches the name of IngressClass.
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: game-2048-node-port-service
                port:
                  number: 80